custom_cursor_colors: true
colors:
  # Default colors
  primary:
    background: '#000000'
    # Standard light gray
    foreground: '0xeaeaea'
    # This is the green foreground color that we sometimes like to use.
    # foreground: '0x00FF00'

    # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xcd0000'
    green:   '0x00cd00'
    yellow:  '0xcdcd00'
    blue:    '0x0000ee'
    magenta: '0xcd00cd'
    cyan:    '0x00cdcd'
    white:   '0xe5e5e5'

    # Bright colors
    bright:
      black:   '0x7f7f7f'
      red:     '0xff0000'
      green:   '0x00ff00'
      yellow:  '0xffff00'
      blue:    '0x5c5cff'
      magenta: '0xff00ff'
      cyan:    '0x00ffff'
      white:   '0xffffff'
      colors:
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'

font:
  normal:
    family: Hack Nerd Font
  bold:
    family: Hack Nerd Font
  italic:
    family: Hack Nerd Font

key_bindings:
  - { key: K, mods: Command, chars: "clear\n" }
